project:
  type: website
  output-dir: docs

website:
  title: "PM566 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: "Final Report"
      - href: data-processing.qmd
        text: "About the Data"

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true

editor: visual

